version: '3'
services:
  myapp:
    container_name: myapp
    image: myapp_dev14
    build:
      context: .
      dockerfile: .docker/nginx.dev.dockerfile
    command: npm start
    volumes:
      - .:/ng-app      
    ports:
      - "80:80"
      - "443:443"

    networks:
      - app-network

  server:
    container_name: server
    image: server
    build:
      context: ./Server
      dockerfile: .docker/node.development.dockerfile
    volumes:
      - ./Server:/usr/src/app 
    ports:
      - "3000:3000"
    depends_on:
      - mongodb  
   
    networks:
      - app-network
      
  mongodb:
    container_name: mongodb
    image: mongo:3.4.2
    volumes:
     - db-data:/data/db
    networks:
      - app-network
    restart: always
    command: mongod --smallfiles --logpath=/dev/null # --quiet 
volumes:
    db-data:

networks:
  app-network:
    driver: bridge

