version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:3.4.2
    
    volumes:
      -/home/bschoi/mongodb:/data/db
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_PASSWORD: sage123
      MONGO_INITDB_ROOT_USERNAME: admin
    networks:
      - app-network
    command: [--auth]  
#    command: mongod --smallfiles --logpath=/dev/null # --quiet 
    
  myapp:
    container_name: myapp1
    image: myapp_dev14
    build:
      context: .
      dockerfile: .docker/nginx.dev.dockerfile
    command: npm start
    volumes:
      - .:/ng-app      
    ports:
      - "8083:8083"
      - "443:443"
      - "80:80"

    networks:
      - app-network

  server:
    container_name: server
    image: server
    build:
      context: ./Server
      dockerfile: .docker/node.development.dockerfile
    volumes:
      - ./Server:/usr/src/app 
    ports:
      - "3000:3000"
    depends_on:
      - mongodb  
   
    networks:
      - app-network
      
 
#volumes:
#    db-data:

networks:
  app-network:
    driver: bridge

